version: '2'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.4
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config:/usr/share/elasticsearch/config
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./plugins:/usr/share/elasticsearch/plugins

  kibana:
    container_name: kibana
    image: kibana:5.4
    ports:
      - "5601:5601"
    links:
      - elasticsearch
