http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
#


cluster.name: dev-autocomplete

node.name: ${HOSTNAME}

path.data: /usr/share/elasticsearch/data

path.logs: /usr/share/elasticsearch/logs
